### ISSUE TITLE
 Sporadic Connection issues between AWS Thing (ESP32) and Greengrass Core device

### ISSUE THREAD

**Issue by mleister97** [aws/aws-iot-device-sdk-embedded-C#1727]
I am trying to setup a MQTT connection between an AWS Thing (ESP32) and my greengrass core device.
- Sometimes the ESP is not even able to connect to the greengrass core device.
- Most of the time it is possible to connect to the greengrass device but I am not able to receive any messages (The ESP32 logs showing the log "Publishing successful")
- In some rare cases I can connect and I am also able to receive messages on the core device. 

Really weird situation as I face different cases without changing any code. Any help appreciated. Running a **python example script** from my computer using the same hostname, certificates and so on is working fine always as expected.

I am using the library https://github.com/aws-samples/arduino-aws-greengrass-iot, which is based on this one.

Logs from greengrass core when I cannot even connect
```
2021-09-24T13:31:01.970Z [ERROR] (nioEventLoopGroup-3-8) io.moquette.broker.NewNettyMQTTHandler: Unexpected exception while processing MQTT message. Closing Netty channel. CId=null. {}
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLProtocolException: Empty HostName in server_name extension
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.moquette.broker.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:51)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLProtocolException: Empty HostName in server_name extension
        at java.base/sun.security.ssl.ServerNameExtension$CHServerNamesSpec.<init>(ServerNameExtension.java:124)
        at java.base/sun.security.ssl.ServerNameExtension$CHServerNameConsumer.consume(ServerNameExtension.java:296)
        at java.base/sun.security.ssl.SSLExtension.consumeOnLoad(SSLExtension.java:593)
        at java.base/sun.security.ssl.SSLExtensions.consumeOnLoad(SSLExtensions.java:189)
        at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1062)
        at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:854)
        at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
        at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1557)
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1571)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1455)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
```

Logs from greengrass core when I am not able to receive messages (Note: The client is allowed to publish actually, sometimes it is working fine as well)
```
2021-09-24T13:21:39.571Z [ERROR] (nioEventLoopGroup-3-6) io.moquette.broker.PostOffice: client is not authorized to publish on topic: clients/IoTDeviceESP32/hello/world. {}
2021-09-24T13:21:44.962Z [ERROR] (nioEventLoopGroup-3-6) com.aws.greengrass.mqttbroker.ClientDeviceAuthorizer: Unknown client request, denying request. {clientId=IoTDeviceESP32, resource=mqtt:topic:clients/IoTDeviceESP32/hello/world, operation=mqtt:publish}
```

**Comment by dan4thewin** [comment]
Hi, @mleister97 .  I'm sorry to say that the library you're using appears to be based on very old code.  I recommend you consider using coreMQTT on top of FreeRTOS.

**Comment by mleister97** [comment]
Thanks, working fine. Someone should mention that this library **is not working with Greengrass V2** in the readme file.
